// packages/atom.io/src/solid/use-single-effect.ts
/** biome-ignore-all lint/correctness/useHookAtTopLevel: intentional */

import { isFn } from "atom.io/internal"
import { createEffect } from "solid-js"

export function useSingleEffect(
	effect: () => (() => void) | undefined | void,
	deps: unknown[],
): void {
	const globalEnv = (globalThis as unknown as { env: any })[`env`]
	const isInDev = globalEnv?.NODE_ENV === `development`
	if (isInDev) {
		const cleanupRef: false | (() => void) = false
		createEffect(() => {
			let cleanupFn = cleanupRef
			if (cleanupFn === false) {
				cleanupFn = effect() ?? true
				cleanupRef.current = cleanupFn
			} else {
				return () => {
					if (isFn(cleanupFn)) cleanupFn()
					cleanupRef.current = false
				}
			}
		}, deps)
	} else {
		React.useEffect(effect, deps)
	}
}

// packages/atom.io/realtime-react/src/use-single-effect.ts
import * as React from "react"

const { NODE_ENV } = globalThis.env ?? {}
const IN_DEV = NODE_ENV === `development`

function noop() {}

export function useSingleEffect(
	effect: () => (() => void) | undefined,
	deps: unknown[],
): void {
	if (IN_DEV) {
		const cleanup = React.useRef<() => void>(noop)
		React.useEffect(() => {
			let dispose = cleanup.current
			if (dispose === noop) {
				dispose = effect() ?? noop
				cleanup.current = dispose
			} else {
				return () => {
					dispose()
					cleanup.current = noop
				}
			}
		}, deps)
	} else {
		React.useEffect(effect, deps)
	}
}
