// packages/atom.io/src/solid/use-single-effect.ts
/** biome-ignore-all lint/correctness/useHookAtTopLevel: intentional */

import { isFn } from "atom.io/internal"
import { createEffect } from "solid-js"

export function useSingleEffect(
	effect: () => (() => void) | undefined | void,
	deps: unknown[],
): void {
	const globalEnv = (globalThis as unknown as { env: any })[`env`]
	const isInDev = globalEnv?.NODE_ENV === `development`
	if (isInDev) {
		const cleanupRef: false | (() => void) = false
		createEffect(() => {
			let cleanupFn = cleanupRef
			if (cleanupFn === false) {
				cleanupFn = effect() ?? true
				cleanupRef.current = cleanupFn
			} else {
				return () => {
					if (isFn(cleanupFn)) cleanupFn()
					cleanupRef.current = false
				}
			}
		}, deps)
	} else {
		React.useEffect(effect, deps)
	}
}

// packages/atom.io/src/realtime-react/use-single-effect.ts
/** biome-ignore-all lint/correctness/useHookAtTopLevel: intentional */

import { isFn } from "atom.io/internal/is-fn"
import * as React from "react"

export function useSingleEffect(
	effect: () => (() => void) | undefined | void,
	deps: unknown[],
): void {
	const globalEnv = (globalThis as unknown as { env: any })[`env`]
	const isInDev = globalEnv?.NODE_ENV === `development`
	if (isInDev) {
		const cleanupRef = React.useRef<boolean | (() => void)>(false)
		React.useEffect(() => {
			let cleanupFn = cleanupRef.current
			if (cleanupFn === false) {
				cleanupFn = effect() ?? true
				cleanupRef.current = cleanupFn
			} else {
				return () => {
					if (isFn(cleanupFn)) cleanupFn()
					cleanupRef.current = false
				}
			}
		}, deps)
	} else {
		React.useEffect(effect, deps)
	}
}
