// packages/atom.io/src/solid/store-context.ts
import type { RootStore } from "atom.io/internal"
import { IMPLICIT } from "atom.io/internal"
import type { Context, FlowProps, JSX } from "solid-js"
import { createContext } from "solid-js"

export const StoreContext: Context<RootStore> = createContext(IMPLICIT.STORE)

export function StoreProvider({
	children,
	store = IMPLICIT.STORE,
}: FlowProps<{
	store?: RootStore
}>): JSX.Element {
	return StoreContext.Provider({ value: store, children })
}

// packages/atom.io/react/src/store-context.tsx
import type { Store } from "atom.io/internal"
import { IMPLICIT } from "atom.io/internal"
import * as React from "react"

export const StoreContext: React.Context<Store> = React.createContext(
	IMPLICIT.STORE,
)

export const StoreProvider: React.FC<{
	children: React.ReactNode
	store?: Store
}> = ({ children, store = IMPLICIT.STORE }) => (
	<StoreContext.Provider value={store}>{children}</StoreContext.Provider>
)
