// packages/atom.io/src/solid/use-json.ts
import type { MutableAtomFamilyToken, MutableAtomToken } from "atom.io"
import type { AsJSON, Transceiver } from "atom.io/internal"
import { findInStore, getJsonToken } from "atom.io/internal"
import type { Canonical, Json } from "atom.io/json"
import { useContext } from "solid-js"

import { StoreContext } from "./store-context"
import { useO } from "./use-o"

export function useJSON<T extends Transceiver<any, any, any>>(
	token: MutableAtomToken<T>,
): () => AsJSON<T>

export function useJSON<
	T extends Transceiver<any, any, any>,
	K extends Canonical,
>(token: MutableAtomFamilyToken<T, K>, key: NoInfer<K>): () => AsJSON<T>

export function useJSON(
	token: MutableAtomFamilyToken<any, any> | MutableAtomToken<any>,
	key?: Canonical,
): () => Json.Serializable {
	const store = useContext(StoreContext)
	const stateToken: MutableAtomToken<any> =
		token.type === `mutable_atom_family` ? findInStore(store, token, key) : token
	const jsonToken = getJsonToken(store, stateToken)
	return useO(jsonToken)
}

// packages/atom.io/react/src/use-json.ts
import type {
	MutableAtomFamilyToken,
	MutableAtomToken,
	ReadableToken,
} from "atom.io"
import { findInStore, getJsonToken } from "atom.io/internal"
import type { Canonical, Json } from "atom.io/json"
import * as React from "react"

import { StoreContext } from "./store-context"
import { useO } from "./use-o"

export function useJSON<Serializable extends Json.Serializable>(
	token: MutableAtomToken<any, Serializable>,
): Serializable

export function useJSON<
	Serializable extends Json.Serializable,
	Key extends Canonical,
>(token: MutableAtomFamilyToken<any, Serializable, Key>, key: Key): Serializable

export function useJSON<
	Serializable extends Json.Serializable,
	Key extends Canonical,
>(
	token:
		| MutableAtomFamilyToken<any, Serializable, Key>
		| MutableAtomToken<any, Serializable>,
	key?: Key,
): Serializable {
	const store = React.useContext(StoreContext)
	const stateToken: ReadableToken<any> =
		token.type === `mutable_atom_family`
			? findInStore(store, token, key as Key)
			: token
	const jsonToken = getJsonToken(store, stateToken)
	return useO(jsonToken)
}
