// packages/atom.io/solid/src/use-tl.solid.ts
import type { TimelineToken } from "atom.io"
import {
	arbitrary,
	subscribeToTimeline,
	timeTravel,
	withdraw,
} from "atom.io/internal"
import { createEffect, createSignal, onCleanup, useContext } from "solid-js"

import { StoreContext } from "./store-context-provider.solid"
import { useSyncExternalStore } from "./use-sync-external-store.solid"

export type TimelineMeta = {
	at: () => number
	length: () => number
	undo: () => void
	redo: () => void
}

export function useTL(token: TimelineToken<any>): TimelineMeta {
	const store = useContext(StoreContext)
	const id = arbitrary()
	const tl = withdraw(token, store)
	const undo = () => {
		timeTravel(`undo`, token, store)
	}
	const redo = () => {
		timeTravel(`redo`, token, store)
	}

	const [at, setAt] = createSignal(tl.at)
	const [length, setLength] = createSignal(tl.history.length)

	createEffect(() => {
		const update = () => {
			setAt(tl.at)
			setLength(tl.history.length)
		}
		const unsubscribeFromTimeline = subscribeToTimeline(
			token,
			update,
			`use-tl:${id}`,
			store,
		)

		update()

		onCleanup(() => {
			unsubscribeFromTimeline()
		})
	})

	return { at, length, undo, redo }
}

// packages/atom.io/react/src/use-tl.ts
import { redo, undo } from "atom.io"
import type { TimelineToken } from "atom.io"
import { subscribeToTimeline, withdraw } from "atom.io/internal"
import * as React from "react"

import { StoreContext } from "./store-context"

export type TimelineMeta = {
	at: number
	length: number
	undo: () => void
	redo: () => void
}

export function useTL(token: TimelineToken<any>): TimelineMeta {
	const store = React.useContext(StoreContext)
	const id = React.useId()
	const timeline = withdraw(token, store)
	const tokenRef = React.useRef(token)
	const rebuildMeta = () => {
		return {
			at: timeline.at,
			length: timeline.history.length,
			undo: () => {
				undo(token)
			},
			redo: () => {
				redo(token)
			},
		}
	}
	const meta = React.useRef<TimelineMeta>(rebuildMeta())
	const retrieve = () => {
		if (
			meta.current.at !== timeline?.at ||
			meta.current.length !== timeline?.history.length ||
			tokenRef.current !== token
		) {
			tokenRef.current = token
			meta.current = rebuildMeta()
		}
		return meta.current
	}
	return React.useSyncExternalStore<TimelineMeta>(
		(dispatch) => subscribeToTimeline(token, dispatch, `use-tl:${id}`, store),
		retrieve,
		retrieve,
	)
}
